### ISSUE TITLE
Config file seperate

### ISSUE THREAD

**Issue by Cronus89** [danodemano/Tron-Mirror#1]
Could you seperate the configuration options into its own file so I can easily keep my script updated via git?

**Comment by danodemano** [comment]
I should be able to do that.  Any preference for a type?  I'm thinking a simple .ini is probably sufficient.

**Comment by Cronus89** [comment]
No preference here :)

**Comment by danodemano** [comment]
@Cronus89 script updated to use external config file.  Use caution if uploading the .ini from a Windows machine as it may bork the linebreaks.  Make sure you convert them.  The tronupdate.sh is expecting the .ini in the same directory.  Please let me know if you encounter any issues!
